### ISSUE TITLE
setup.py install_requires is empty

### ISSUE THREAD

**Issue by huard** [Ouranosinc/pyPavics#22]
Review requirements.txt file, remove cruft, and define minimal requirements in install_requires.

**Comment by huard** [comment]
See branch https://github.com/Ouranosinc/pyPavics/tree/issue_22
Issue is that setting specific package versions breaks the install. Conda can't find a matching environment, even if the versions perfectly match those that are installed...

**Comment by fmigneault** [comment]
Running `conda install --file requirements.txt` works on my side, cannot reproduce said issue.
What is the problem exactly?

**Comment by huard** [comment]
The big picture is that I'd like `python setup.py install` to install a minimum set of dependencies so the module can at least be imported without raising an import error. 
This will hopefully facilitate automated installation in ReadtheDocs virtualenvs. 

The problem in the issue_22 branch is that I've had to remove the package versions from requirements.txt, which goes against best practices because package versions might change without proper validation. 

I'm not strongly attached to having the requirements in the install_require if we can find another way to install dependencies on ReadtheDocs. 

Note that the version in master is missing some dependencies (threddsclient, requests,shapely). This causes no error in prod because they're installed by the pavics_datacatalog Dockerfile.

**Comment by fmigneault** [comment]
Packages with proper package versions are found using : 
```
conda activate <pypavics-env>
pip install -r requirements.txt
```

**Comment by fmigneault** [comment]
Even better, automated import of requirements in : 
https://github.com/Ouranosinc/pyPavics/tree/issue_22_fix-make-install-packages

Only following call will install and build everything with proper dependency versions:
```
conda activate <pypavics-env>
make install
```
